### ISSUE TITLE
Cannot find  the "Microsoft.VCLibs.ARM64.14.00.appx"  ?

### ISSUE THREAD

**Issue by thienphuoc** [tgckpg/libtranslate#1]
Hi !

When I build the project I can not find "AppX-Retail-ARM64=.\AppX\Retail\ARM64\Microsoft.VCLibs.ARM64.14.00.appx" ?

Can you give me your w10 sdk version ?

**Comment by tgckpg** [comment]
The SDK shouldn't matter. It can be built by just targeting 10.0.10240.0.

Also this is a dynamic library ( .dll ). Why are you trying to find an appx file? To use the library, you'll have to add this project ( or the compiled dll ) in your solution and reference it.

Anyway, just in case if you still need to know the SDK version I was using, it's 10.0.14393.0.

**Comment by thienphuoc** [comment]
Honestly , I'm trying to build ARM64 appx to run on another machine. But missing the "Retail\ARM64\Microsoft.VCLibs.ARM64.14.00.appx" ! 

I don't know how to get it ! 

Can you give me the Retail folder (.zip) in 
C:\Program Files (x86)\Microsoft SDKs\Windows Kits\10\ExtensionSDKs\Microsoft.VCLibs\14.0\Appx\Retail

I'm grateful to you for your help ! Thanks you very much ! tgckpg !

Phuoc !

**Comment by tgckpg** [comment]
I see. I've got one already ( It was for offline install of one of my apps ). It should be the same.

[Here](https://file.astropenguin.net/public/Grimoire%20Reaper/), inside the Dependencies folder. ( remember to validate the hashsum )

**Comment by thienphuoc** [comment]
Thanks for your help ! tgckpg ! (y)
Phuoc !
